version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/fhir-mapbuilder-validation"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/vscode-extension"
    schedule:
      interval: "weekly"
