name: Publish VS Code Extension

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1

      - name: Install dependencies
        run: npm install
        working-directory: vscode-extension

      - name: Compile TypeScript
        run: npm run compile
        working-directory: vscode-extension

      - name: Install vsce
        run: npm install -g vsce

      - name: Debug Token Presence
        run: echo "Token length = ${#P_A_T}"
        env:
          P_A_T: ${{ secrets.P_A_T }}

      - name: Publish to Marketplace
        shell: bash
        env:
          P_A_T: ${{ secrets.P_A_T }}
        run: vsce publish -p "$P_A_T"
        working-directory: vscode-extension
